kind: pipeline
name: ci
type: docker
steps:
  - name: testing
    image: golang:1.18
    environment:
      DESIRED_VERSION: v3.8.1
    commands:
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh && ./get_helm.sh
      - make
    when:
      event:
        - pull_request
